[workspace]
resolver = "2"
members = [
    "crates/*"
]

[workspace.dependencies]
tsp-core = {path = "crates/tsp-core"}
tsp-parser = {path = "crates/tsp-parser"}
tsp-solvers = {path = "crates/tsp-solvers"}
traveling-crab = {path = "."}